meta_product_name: "Je Note Mon Camping Car"
meta_title: "Partage d'avis & d'expériences - Camping-Car, Van, Fourgon, Caravane"
meta_description: "L'achat d'un camping car, d'un van ou d'un fourgon aménagé nécéssite une longue réfléxion. Pour vous aider, consultez les avis laissé par d'autres membres de la communauté."
meta_image: "meta_tag.jpeg" # should exist in `app/assets/images/`
